---
id: gunmaweb12
base_name: trpg-is-agile
tags:
- TRPG
presentation_date: 2013/02/09
version: 2013.02.09
licenses: []
slideshare_id: 
speaker_deck_id: 
author:
  markup_language: :rd
  name: parrot-studio
  email: parrot.studio.dev@gmail.com
  rubygems_user: 
  slideshare_user: parrotstudio
  speaker_deck_user: 
